In [61]:
import numpy as np
import pandas as pd

In [62]:
p=0.9
mat = pd.read_csv("data.csv", header=None)
mat

    0   1   2   3   4   5   6   7
0   0   5  10  15  20  30  40  50
1  20   5   7   8   8   9   9   9
2  30   9  13  16  17  18  19  19
3  40  14  21  25  28  31  33  33
4  50  19  29  36  40  45  48  50
5  60  24  37  47  54  62  67  69

In [63]:
cov_mat=np.cov(mat.T)
cov_mat

array([[466.66666667, 157.33333333, 228.        , 272.        ,
        292.66666667, 286.        , 258.        , 208.66666667],
       [157.33333333,  60.26666667,  90.6       , 111.8       ,
        125.13333333, 132.8       , 132.4       , 124.13333333],
       [228.        ,  90.6       , 137.5       , 171.1       ,
        193.3       , 208.9       , 212.4       , 204.2       ],
       [272.        , 111.8       , 171.1       , 214.7       ,
        244.5       , 268.3       , 277.2       , 271.8       ],
       [292.66666667, 125.13333333, 193.3       , 244.5       ,
        280.96666667, 313.3       , 329.        , 328.66666667],
       [286.        , 132.8       , 208.9       , 268.3       ,
        313.3       , 359.5       , 388.        , 399.8       ],
       [258.        , 132.4       , 212.4       , 277.2       ,
        329.        , 388.        , 429.6       , 454.8       ],
       [208.66666667, 124.13333333, 204.2       , 271.8       ,
        328.66666667, 399.8       , 454.8       , 495.06666667]])

In [64]:
eigen_vals, eigen_vecs = np.linalg.eig(cov_mat)
eigen_vecs = eigen_vecs / np.linalg.norm(eigen_vecs, axis=0, keepdims=True)

sorted_idx = np.argsort(eigen_vals)[::-1]
eigen_vals = eigen_vals[sorted_idx]
eigen_vecs = eigen_vecs[:, sorted_idx]
eigen_vals,eigen_vecs

(array([ 2.11380192e+03,  3.30082631e+02,  2.47211949e-01,  9.09209489e-02,
         4.39841254e-02,  6.37073897e-14,  4.17014596e-14, -1.04198506e-13]),
 array([[ 0.36123931, -0.76033678,  0.0737107 , -0.1410723 , -0.12070775,
         -0.11236544,  0.05363365,  0.29378199],
        [ 0.15910083, -0.1428599 , -0.22142557,  0.34831514, -0.033064  ,
         -0.709161  ,  0.5048046 , -0.79693479],
        [ 0.24742971, -0.15572268, -0.41087965,  0.69237472,  0.07913265,
          0.47694441, -0.34398732,  0.30913802],
        [ 0.31473212, -0.12620752, -0.34517507, -0.53047837,  0.20676062,
          0.3534928 , -0.45327779, -0.13242329],
        [ 0.36382308, -0.05916556,  0.16171483, -0.15009255, -0.32196947,
         -0.07844261,  0.40927883, -0.34263475],
        [ 0.41012625,  0.10826142,  0.47561573,  0.11586122,  0.75602716,
         -0.08001148,  0.09364362, -0.0473114 ],
        [ 0.4353008 ,  0.29643942,  0.41114843,  0.17515001, -0.50974797,
          0.22878221, -0.41057318,  0.11720257],
        [ 0.44029279,  0.50813748, -0.48596758, -0.17707625, -0.01549433,
         -0.25910457,  0.2714021 ,  0.17919672]]))

In [65]:
s=0
num_pcs=0
for i in range(len(eigen_vals)):
    s+=eigen_vals[i]
    if s/sum(eigen_vals) >= p:
        num_pcs=i+1
        break


num_pcs

2

In [66]:
principal_vecs = eigen_vecs[:, :num_pcs]

X=mat.to_numpy()
X=X-X.mean(axis=0)
new_pcs = X @ principal_vecs

new_pcs = pd.DataFrame(
    new_pcs,
    columns=[f"PC{i + 1}" for i in range(num_pcs)]
)
new_pcs

         PC1        PC2
0 -15.598932  36.424994
1 -55.844417  -9.017883
2 -31.871705 -10.649055
3  -1.059776  -9.327717
4  32.911747  -6.388847
5  71.463083  -1.041491